version: '3.7'

services:

    
    web:

        build: .
        command: python /hacker-moon/manage.py runserver 0.0.0.0:8000

        volumes:

          - .:/hacker-moon

        ports:

          - 8000:8000

        depends_on:
            - db

    db:
        image: postgres:11

        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"    
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
        
